#!/bin/bash
# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# Generate the gateway environment and TOML configuration files on first start.
#
# Called from the systemd ExecStartPre directive to bootstrap the
# gateway configuration. Idempotent: exits immediately if the file
# already exists.
#
# Usage:
#   init-gateway-env.sh <env-file>
#
# The generated file contains commented defaults for gateway
# environment variables.

set -euo pipefail

ENV_FILE="${1:?Usage: init-gateway-env.sh <env-file>}"
CONFIG_DIR="$(dirname "${ENV_FILE}")"
CONFIG_FILE="${CONFIG_DIR}/gateway.toml"
STATE_HOME="${XDG_STATE_HOME:-${HOME}/.local/state}"
RUNTIME_HOME="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"

write_gateway_config() {
    if [ -f "${CONFIG_FILE}" ]; then
        return
    fi

    mkdir -p "${CONFIG_DIR}" "${STATE_HOME}/openshell/vm-driver"
    cat > "${CONFIG_FILE}" << EOF
[openshell]
version = 1

[openshell.gateway]
compute_drivers = ["podman"]
default_image = "ghcr.io/nvidia/openshell-community/sandboxes/base:latest"
supervisor_image = "ghcr.io/nvidia/openshell/supervisor:latest"
guest_tls_ca = "${STATE_HOME}/openshell/tls/ca.crt"
guest_tls_cert = "${STATE_HOME}/openshell/tls/client/tls.crt"
guest_tls_key = "${STATE_HOME}/openshell/tls/client/tls.key"

[openshell.drivers.podman]
socket_path = "${RUNTIME_HOME}/podman/podman.sock"
image_pull_policy = "missing"
network_name = "openshell"
stop_timeout_secs = 10

[openshell.drivers.vm]
state_dir = "${STATE_HOME}/openshell/vm-driver"
driver_dir = "/usr/libexec/openshell"
grpc_endpoint = "https://127.0.0.1:8080"
EOF
    chmod 600 "${CONFIG_FILE}"
}

ensure_env_points_at_config() {
    if grep -q '^OPENSHELL_GATEWAY_CONFIG=' "${ENV_FILE}"; then
        return
    fi

    cat >> "${ENV_FILE}" << EOF

# Gateway TOML configuration. Driver implementation settings live here.
OPENSHELL_GATEWAY_CONFIG=${CONFIG_FILE}
EOF
}

# ── Idempotent: skip if env file already exists ─────────────────────
if [ -f "${ENV_FILE}" ]; then
    write_gateway_config
    ensure_env_points_at_config
    exit 0
fi

# ── Create parent directory ─────────────────────────────────────────
mkdir -p "${CONFIG_DIR}"
write_gateway_config

# ── Write environment file ──────────────────────────────────────────
cat > "${ENV_FILE}" << EOF
# OpenShell Gateway Environment Configuration
# Generated on first start. Edit freely; this file is not overwritten.
#
# Run 'openshell-gateway --help' for the full list of options.
# See /usr/share/doc/openshell-gateway/ for guides.

OPENSHELL_GATEWAY_CONFIG=${CONFIG_FILE}

# ---- Optional (uncomment to override defaults) ----

# Database URL for gateway state persistence.
# Default for the user unit: sqlite://\$XDG_STATE_HOME/openshell/gateway.db
#OPENSHELL_DB_URL=sqlite:///path/to/gateway.db

# Compute driver: podman (default for RPM), docker, kubernetes, vm.
#OPENSHELL_DRIVERS=podman

# Bind address. 0.0.0.0 listens on all interfaces; mTLS prevents
# unauthenticated access.
#OPENSHELL_BIND_ADDRESS=0.0.0.0

# API port (default: 8080).
#OPENSHELL_SERVER_PORT=8080

# Log level: trace, debug, info, warn, error.
#OPENSHELL_LOG_LEVEL=info

# Driver implementation settings, including images, pull policy, Podman
# socket, TLS mounts, and VM paths, live in:
# ${CONFIG_FILE}

# ---- TLS (mTLS enabled by default) ----
# PKI is auto-generated by 'openshell-gateway generate-certs' from the
# unit's ExecStartPre on first start. Client certs are placed in
# ~/.config/openshell/gateways/openshell/mtls/ so the CLI discovers them
# automatically.
#
# To use externally-managed certs, uncomment and edit the paths below.
# To rotate certs, delete ~/.local/state/openshell/tls/ and restart.
# WARNING: Disabling TLS with the default bind address (0.0.0.0) exposes
# the gateway API to the entire network with NO authentication. Only
# disable TLS when behind a TLS-terminating reverse proxy, or restrict
# OPENSHELL_BIND_ADDRESS to 127.0.0.1.
#OPENSHELL_DISABLE_TLS=true

# Server TLS (gateway listens with these certs).
#OPENSHELL_TLS_CERT=\$XDG_STATE_HOME/openshell/tls/server/tls.crt
#OPENSHELL_TLS_KEY=\$XDG_STATE_HOME/openshell/tls/server/tls.key
#OPENSHELL_TLS_CLIENT_CA=\$XDG_STATE_HOME/openshell/tls/ca.crt

# Comma-separated DNS SANs configured on the gateway server certificate.
# Wildcard DNS SANs also enable sandbox service URLs under that domain.
# Example: OPENSHELL_SERVER_SAN=*.apps.example.com
#OPENSHELL_SERVER_SAN=

EOF

chmod 600 "${ENV_FILE}"
echo "Gateway environment generated: ${ENV_FILE}"
